import type { ThemePreset } from "../registry.ts";

export const atelierThemePreset: ThemePreset = {
  key: "atelier",
  label: "Atelier",
  description: "Digital Curator: tonal monochrome with intentional golden accents.",
  tokens: {
    canvas: "#F9F9F9",
    surface: "#F9F9F9",
    surfaceAlt: "#E8E8E8",
    surfaceStrong: "#FFFFFF",
    textPrimary: "#1A1C1C",
    textMuted: "#5E5E5E",
    textInverse: "#FFFFFF",
    border: "#E5E5E5",
    borderStrong: "#D4D4D4",
    primary: "#E8A811",
    primaryForeground: "#000000",
    accent: "#E8A811",
    accentForeground: "#000000",
    success: "#006630",
    successForeground: "#FFFFFF",
    danger: "#BA1A1A",
    dangerForeground: "#FFFFFF",
    navSolidBg: "#F9F9F9",
    navSolidFg: "#1A1C1C",
    navSolidInteractive: "#E8A811",
    focusRing: "#E8A811",
    shadowSoft: "0 20px 40px rgba(0, 0, 0, 0.04)",
  },
  components: {
    button: {
      primaryBg: "#E8A811",
      primaryFg: "#000000",
      primaryHoverBg: "#C8910E",
      secondaryBg: "transparent",
      secondaryFg: "#E8A811",
      secondaryHoverBg: "transparent",
      outlineBg: "transparent",
      outlineFg: "#1A1C1C",
      outlineBorder: "rgba(186, 194, 201, 0.15)",
      outlineHoverBg: "transparent",
      outlineHoverFg: "#E8A811",
      ghostFg: "#E8A811",
      ghostHoverBg: "transparent",
      ghostHoverFg: "#E8A811",
      destructiveBg: "#BA1A1A",
      destructiveFg: "#FFFFFF",
      destructiveHoverBg: "#93000A",
      linkFg: "#E8A811",
      linkHoverFg: "#C8910E",
    },
  },
  typography: {
    headingFamily: "Manrope",
    bodyFamily: "Inter",
    headingFallback: "system-ui, sans-serif",
    bodyFallback: "system-ui, sans-serif",
  },
  radius: {
    sm: "0.125rem",
    md: "0.25rem",
    lg: "0.5rem",
    pill: "9999px",
  },
};
